name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Cordova CLI
      run: |
        npm install -g cordova@latest
        
    - name: Install project dependencies
      working-directory: okul-app
      run: |
        npm install
        
    - name: Prepare Cordova project
      working-directory: okul-app
      run: |
        cordova platform add android || true
        cordova prepare
        
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true
        
    - name: Install Android SDK components
      run: |
        sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"
        
    - name: Build Debug APK
      working-directory: okul-app
      run: |
        cordova build android --debug
        
    - name: Build Release APK
      working-directory: okul-app
      run: |
        cordova build android --release
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          okul-app/platforms/android/app/build/outputs/apk/debug/*.apk
          okul-app/platforms/android/app/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Create Release (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          okul-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          okul-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}